version: '3'

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - "${IMDR_VIRTUAL_PORT}:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/key.pem
      # Set to the port that your webapp listens on
      VIRTUAL_PORT: ${IMDR_VIRTUAL_PORT}
      # Can be comma-separated list
      VIRTUAL_HOST: ${IMDR_VIRTUAL_HOST}
      # The domain for the cert, can also be comma-separated
      LETSENCRYPT_HOST: ${IMDR_VIRTUAL_HOST}
      # Your email for the cert
      LETSENCRYPT_EMAIL: ${IMDR_LETSENCRYPT_EMAIL}
    volumes:
      - "${IMDR_REGISTRY_VOLUME_HOME}:/var/lib/registry"
      - "${IMDR_AUTH_HOME}:/auth"
      - "${IMDR_CERTS_HOME}:/certs"

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 8080:80
    environment:
      REGISTRY_URL: "https://${IMDR_VIRTUAL_HOST}:${IMDR_VIRTUAL_PORT}"
      SINGLE_REGISTRY: "true"
    depends_on:
      - registry

networks:
  default:
    external:
      name: letsencrypt
