version: '3'

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - /opt/docker/registry/data:/var/lib/registry
      - /opt/docker/registry/auth:/auth

  portainer:
    image: portainer/portainer
    volumes:
      - /opt/docker/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
networks:
  default:
    external:
      name: letsencrypt
